MarineMexico/Models/Inventario.cs
using System;
using System.Collections.Generic;

namespace MarineMexico.Models;

public partial class Inventario
{
    public int Id { get; set; }

    public int ArticuloId { get; set; }

    public int TallaId { get; set; }

    public int StockActual { get; set; }

    public int StockMinimo { get; set; }

    public virtual Articulo Articulo { get; set; } = null!;

    public virtual ICollection<MovimientosInventario> MovimientosInventarios { get; set; } = new List<MovimientosInventario>();

    public virtual Talla Talla { get; set; } = null!;
}

MarineMexico/Models/ViewModels/InventarioViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MarineMexico.Models.ViewModels
{
    public class InventarioViewModel
    {
        [Required]
        public int ArticuloId { get; set; }

        [Required]
        public int TallaId { get; set; }

        [Required]
        public int StockActual { get; set; } = 0;

        [Required]
        public int StockMinimo { get; set; } = 0;
    }
}

MarineMexico/Controllers/InventariosController.cs
using MarineMexico.Data;
using MarineMexico.Models;
using MarineMexico.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarineMexico.Controllers
{
    public class InventariosController : Controller
    {
        private readonly SsamarineContext _context;

        public InventariosController(SsamarineContext context)
        {
            _context = context;
        }

        // GET: Inventarios
        public async Task<IActionResult> Index()
        {
            var ssamarineContext = _context.Inventarios.Include(i => i.Articulo).Include(i => i.Talla);
            return View(await ssamarineContext.ToListAsync());
        }

        // GET: Inventarios/Create
        public IActionResult Create()
        {
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre");
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion");
            return View();
        }

        // POST: Inventarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ArticuloId,TallaId,StockActual,StockMinimo")] InventarioViewModel inventario)
        {
            if (ModelState.IsValid)
            {
                if (await _context.Inventarios.AnyAsync(i => i.ArticuloId == inventario.ArticuloId && i.TallaId == inventario.TallaId))
                {
                    ModelState.AddModelError("", "Ya existe un inventario para este artículo y talla.");
                    ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
                    ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
                    return View(inventario);
                }

                var nuevoInventario = new Inventario
                {
                    ArticuloId = inventario.ArticuloId,
                    TallaId = inventario.TallaId,
                    StockActual = inventario.StockActual,
                    StockMinimo = inventario.StockMinimo
                };
                _context.Add(nuevoInventario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
            return View(inventario);
        }

        // GET: Inventarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventario = await _context.Inventarios.FindAsync(id);
            if (inventario == null)
            {
                return NotFound();
            }
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
            return View(inventario);
        }

        // POST: Inventarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ArticuloId,TallaId,StockActual,StockMinimo")] Inventario inventario)
        {
            if (id != inventario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inventario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventarioExists(inventario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
            return View(inventario);
        }

        // GET: Inventarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventario = await _context.Inventarios
                .Include(i => i.Articulo)
                .Include(i => i.Talla)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inventario == null)
            {
                return NotFound();
            }

            return View(inventario);
        }

        // POST: Inventarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Este DELETE activa el trigger INSTEAD OF DELETE tr_Inventario_PreventDelete
            await _context.Database.ExecuteSqlRawAsync("DELETE FROM Inventario WHERE Id = @p0", id);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool InventarioExists(int id)
        {
            return _context.Inventarios.Any(e => e.Id == id);
        }
    }
}

MarineMexico/Controllers/MovimientosInventariosController.cs
using MarineMexico.Data;
using MarineMexico.Models;
using MarineMexico.Models.ViewModels;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarineMexico.Controllers
{
    public class MovimientosInventariosController : Controller
    {
        private readonly SsamarineContext _context;

        public MovimientosInventariosController(SsamarineContext context)
        {
            _context = context;
        }

        // GET: MovimientosInventarios
        public async Task<IActionResult> Index(int? inventarioId = null)
        {
            var query = _context.MovimientosInventarioViews.AsQueryable();

            if (inventarioId.HasValue)
            {
                query = query.Where(x => x.InventarioId == inventarioId);

                var inventario = await _context.Inventarios
                    .Include(x => x.Articulo)
                    .Include(x => x.Talla)
                    .FirstAsync(x => x.Id == inventarioId);

                ViewBag.Inventario = $"{inventario.Articulo.Nombre} | Talla: {inventario.Talla.Descripcion}";
            }

            var ssamarineContext = await query.ToListAsync();

            return View(ssamarineContext);
        }

        // GET: MovimientosInventarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientosInventario = await _context.MovimientosInventarios
                .Include(m => m.Empleado)
                .Include(m => m.Inventario)
                .Include(m => m.TipoMovimiento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movimientosInventario == null)
            {
                return NotFound();
            }

            return View(movimientosInventario);
        }

        // GET: MovimientosInventarios/Create
        public IActionResult Create()
        {
            SetViewDataForCreate();
            return View();
        }

        private void SetViewDataForCreate()
        {
            ViewData["Empleado"] = _context.Empleados
                .Include(x => x.IdGrupoNavigation.IdTipoNavigation)
                .OrderBy(x => x.NombreEmpleado)
                .AsEnumerable()
                .Select(x => new
                {
                    x.IdEmpleado,
                    NombreEmpleado = $"{x.NombreEmpleado} ({x.IdGrupoNavigation.IdTipoNavigation.Tipo})",
                    x.IdGrupoNavigation.IdTipo
                })
                .ToList();

            ViewData["Inventario"] = _context.Inventarios
                .Include(x => x.Articulo)
                .Include(x => x.Articulo.TipoEmpleado)
                .Include(x => x.Talla)
                .Select(x => new
                {
                    x.Id,
                    Descripcion = $"{x.Articulo.Nombre} | {x.Talla.Talla1} ({x.Talla.Notacion}) | {(x.Articulo.TipoEmpleadoId.HasValue ? x.Articulo.TipoEmpleado.Tipo : "Sin Tipo")}",
                    x.Articulo.TipoEmpleadoId,
                    Tipo = x.Articulo.TipoEmpleado != null ? x.Articulo.TipoEmpleado.Tipo : "Sin Tipo"
                })
                .ToList();

            ViewData["TipoMovimientoId"] = new SelectList(_context.TiposMovimientoInventarios, "Id", "Descripcion");
            ViewData["MotivoMovimiento"] = _context.MotivosMovimientoInventarios.ToList();
        }

        // POST: MovimientosInventarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TipoMovimientoId,MotivoMovimientoId,Cantidad,InventarioId,FechaMovimiento,EmpleadoId")] MovimientosInventarioViewModel movimientosInventario)
        {
            if (ModelState.IsValid)
            {
                // El tipo de empleado correspondiente al empleado al que se le asigno el movimiento
                int tipoEmpleadoId = await _context.Empleados
                    .Where(e => e.IdEmpleado == movimientosInventario.EmpleadoId)
                    .Select(e => e.IdGrupoNavigation.IdTipo)
                    .FirstOrDefaultAsync();

                // el articulo no corresponde al tipo de empleado
                if (await _context.Inventarios
                    .Where(i => i.Id == movimientosInventario.InventarioId)
                    .Select(i => i.Articulo.TipoEmpleadoId)
                    .AnyAsync(tipo =>
                        tipoEmpleadoId != default
                        && tipo != null
                        && tipo != tipoEmpleadoId))
                {
                    ModelState.AddModelError("", "El artículo no corresponde al tipo de empleado");
                    SetViewDataForCreate();
                    return View(movimientosInventario);
                }

                if (movimientosInventario.TipoMovimientoId == TiposMovimientoInventario.SALIDA)
                {
                    var inv = await _context.Inventarios.FindAsync(movimientosInventario.InventarioId);
                    int stockRestante = inv.StockActual - movimientosInventario.Cantidad;

                    if (stockRestante < inv.StockMinimo)
                    {
                        ModelState.AddModelError("", $"El stock mínimo del artículo en el inventario es: {inv.StockMinimo}");
                        SetViewDataForCreate();
                        return View(movimientosInventario);
                    }

                    if (stockRestante < 0)
                    {
                        ModelState.AddModelError("", "No hay stock suficiente de este artículo en el inventario");
                        SetViewDataForCreate();
                        return View(movimientosInventario);
                    }
                }

                var nuevoMovimientoInventario = new MovimientosInventario
                {
                    TipoMovimientoId = movimientosInventario.TipoMovimientoId,
                    MotivoMovimientoId = movimientosInventario.MotivoMovimientoId,
                    Cantidad = movimientosInventario.Cantidad,
                    InventarioId = movimientosInventario.InventarioId,
                    FechaMovimiento = movimientosInventario.FechaMovimiento,
                    EmpleadoId = movimientosInventario.EmpleadoId
                };

                // Este INSERT activa el trigger [dbo].[tr_MovimientosInventario_After]
                _context.Add(nuevoMovimientoInventario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            SetViewDataForCreate();
            return View(movimientosInventario);
        }

        // GET: MovimientosInventarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientosInventario = await _context.MovimientosInventarios.FindAsync(id);
            if (movimientosInventario == null)
            {
                return NotFound();
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado", movimientosInventario.EmpleadoId);
            ViewData["InventarioId"] = new SelectList(_context.Inventarios, "Id", "Id", movimientosInventario.InventarioId);
            ViewData["TipoMovimientoId"] = new SelectList(_context.TiposMovimientoInventarios, "Id", "Id", movimientosInventario.TipoMovimientoId);
            return View(movimientosInventario);
        }

        // POST: MovimientosInventarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TipoMovimientoId,MotivoMovimientoId,Cantidad,StockActualAntes,InventarioId,FechaMovimiento,EmpleadoId")] MovimientosInventario movimientosInventario)
        {
            if (id != movimientosInventario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movimientosInventario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovimientosInventarioExists(movimientosInventario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "IdEmpleado", "IdEmpleado", movimientosInventario.EmpleadoId);
            ViewData["InventarioId"] = new SelectList(_context.Inventarios, "Id", "Id", movimientosInventario.InventarioId);
            ViewData["TipoMovimientoId"] = new SelectList(_context.TiposMovimientoInventarios, "Id", "Id", movimientosInventario.TipoMovimientoId);
            return View(movimientosInventario);
        }

        // GET: MovimientosInventarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimientosInventario = await _context.MovimientosInventarioViews
                .FirstOrDefaultAsync(m => m.Id == id);

MarineMexico/Views/Inventarios/Create.cshtml
@model MarineMexico.Models.ViewModels.InventarioViewModel

@{
    ViewData["Title"] = "Añadir artículo al inventario";
}

<h1 class="subtitle has-text-weight-normal">@ViewData["Title"]</h1>

<div class="columns">
    <div class="column is-full-mobile is-half-tablet is-one-third-desktop">

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="has-text-danger"></div>
            <div class="field">
                <label class="label">Artículo</label>
                <div class="control">
                    <div class="select">
                        <select asp-for="ArticuloId" asp-items="ViewBag.ArticuloId"></select>
                    </div>
                </div>
            </div>
            <div class="field">
                <label class="label">Talla</label>
                <div class="control">
                    <div class="select">
                        <select asp-for="TallaId" asp-items="ViewBag.TallaId"></select>
                    </div>
                </div>
            </div>
            <div class="field">
                <label asp-for="StockMinimo" class="label">Stock mínimo</label>
                <div class="control">
                    <input asp-for="StockMinimo" class="input" />
                    <span asp-validation-for="StockMinimo" class="text-danger"></span>
                </div>
            </div>
            <div class="field mt-5">
                <input type="submit" value="Añadir" class="button" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al inventario</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarineMexico/Views/Inventarios/Delete.cshtml
@model MarineMexico.Models.Inventario

@{
    ViewData["Title"] = "Eliminar inventario";
}

<h1 class="title has-text-weight-normal">@ViewData["Title"]</h1>

<h3>¿Estás seguro de que deseas eliminar esto?</h3>
<h4 class="is-danger">
    <div class="icon">
        <i class="fa-solid fa-circle-exclamation"></i>
    </div>
    Se eliminará el inventario y sus movimientos
</h4>

<div>
    <hr />

    <div class="field">
        <label class="label">Artículo</label>
        <p>@Model.Articulo.Nombre</p>
    </div>
    <div class="field">
        <label class="label">Talla</label>
        <p>@Model.Talla.Descripcion</p>
    </div>
    <div class="field">
        <label class="label">Stock Actual</label>
        <p>@Model.StockActual</p>
    </div>

    <div class="buttons mt-5">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Eliminar" class="button is-danger mr-3" />
            <a asp-action="Index" class="button is-light">Volver a la lista</a>
        </form>
    </div>
    
</div>

MarineMexico/Views/Inventarios/Index.cshtml
@model IEnumerable<MarineMexico.Models.Inventario>

@{
    ViewData["Title"] = "Inventario";
}

<h1 class="title has-text-weight-normal">@ViewData["Title"]</h1>

<div class="buttons mb-3">
    <a class="button" asp-action="Create" asp-controller="Inventarios">
        <span class="icon mr-1">
            <i class="fa-solid fa-plus"></i>
        </span>
        Agregar
    </a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Artículo</th>
            <th>Talla</th>
            <th>Stock Actual</th>
            <th>Stock Mínimo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Articulo.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Talla.Talla1) (@Html.DisplayFor(modelItem => item.Talla.Notacion))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StockActual)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StockMinimo)
                </td>
                
                <td>
                    <a asp-controller="MovimientosInventarios" asp-action="Index" asp-route-inventarioId="@item.Id">Movimientos</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>