MarineMexico/Controllers/ArticulosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarineMexico.Data;
using MarineMexico.Models;

namespace MarineMexico.Controllers
{
    public class ArticulosController : Controller
    {
        private readonly SsamarineContext _context;

        public ArticulosController(SsamarineContext context)
        {
            _context = context;
        }

        // GET: Articulos
        public async Task<IActionResult> Index()
        {
            var ssamarineContext = _context.Articulos.Include(a => a.TipoEmpleado);
            return View(await ssamarineContext.ToListAsync());
        }

        // GET: Articulos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articulo = await _context.Articulos
                .Include(a => a.TipoEmpleado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (articulo == null)
            {
                return NotFound();
            }

            return View(articulo);
        }

        // GET: Articulos/Create
        public IActionResult Create()
        {
            ViewData["TipoEmpleadoId"] = new SelectList(_context.TiposEmpleados, "IdTipo", "Tipo");
            return View();
        }

        // POST: Articulos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,TipoEmpleadoId")] Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(articulo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoEmpleadoId"] = new SelectList(_context.TiposEmpleados, "IdTipo", "Tipo", articulo.TipoEmpleadoId);
            return View(articulo);
        }

        // GET: Articulos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articulo = await _context.Articulos.FindAsync(id);
            if (articulo == null)
            {
                return NotFound();
            }
            ViewData["TipoEmpleadoId"] = new SelectList(_context.TiposEmpleados, "IdTipo", "Tipo", articulo.TipoEmpleadoId);
            return View(articulo);
        }

        // POST: Articulos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,TipoEmpleadoId")] Articulo articulo)
        {
            if (id != articulo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // revisar si existen movimientos con empleados (debido al tipos)
                    if (await _context.MovimientosInventarios.AnyAsync(x =>
                            x.EmpleadoId.HasValue &&
                            x.Inventario.ArticuloId == id
                        ))
                    {
                        ModelState.AddModelError("", "Este artículo ya tiene movimientos de inventario vinculados a empleados, no se puede modificar.");
                        ViewData["TipoEmpleadoId"] = new SelectList(_context.TiposEmpleados, "IdTipo", "Tipo", articulo.TipoEmpleadoId);
                        return View(articulo);
                    }

                    _context.Update(articulo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticuloExists(articulo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoEmpleadoId"] = new SelectList(_context.TiposEmpleados, "IdTipo", "IdTipo", articulo.TipoEmpleadoId);
            return View(articulo);
        }

        // GET: Articulos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articulo = await _context.Articulos
                .Include(a => a.TipoEmpleado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (articulo == null)
            {
                return NotFound();
            }

            return View(articulo);
        }

        // POST: Articulos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var articulo = await _context.Articulos.Include(a => a.TipoEmpleado)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            if (articulo != null)
            {
                if (await _context.Inventarios.AnyAsync(x => x.ArticuloId == id))
                {
                    ModelState.AddModelError("", "No puede eliminar este artículo porque esta registrado en el inventario.");
                    return View(articulo);
                }

                _context.Articulos.Remove(articulo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticuloExists(int id)
        {
            return _context.Articulos.Any(e => e.Id == id);
        }
    }
}

MarineMexico/Controllers/InventariosController.cs
using MarineMexico.Data;
using MarineMexico.Models;
using MarineMexico.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarineMexico.Controllers
{
    public class InventariosController : Controller
    {
        private readonly SsamarineContext _context;

        public InventariosController(SsamarineContext context)
        {
            _context = context;
        }

        // GET: Inventarios
        public async Task<IActionResult> Index()
        {
            var ssamarineContext = _context.Inventarios.Include(i => i.Articulo).Include(i => i.Talla);
            return View(await ssamarineContext.ToListAsync());
        }

        // GET: Inventarios/Create
        public IActionResult Create()
        {
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre");
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion");
            return View();
        }

        // POST: Inventarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ArticuloId,TallaId,StockActual,StockMinimo")] InventarioViewModel inventario)
        {
            if (ModelState.IsValid)
            {
                if (await _context.Inventarios.AnyAsync(i => i.ArticuloId == inventario.ArticuloId && i.TallaId == inventario.TallaId))
                {
                    ModelState.AddModelError("", "Ya existe un inventario para este artículo y talla.");
                    ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
                    ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
                    return View(inventario);
                }

                var nuevoInventario = new Inventario
                {
                    ArticuloId = inventario.ArticuloId,
                    TallaId = inventario.TallaId,
                    StockActual = inventario.StockActual,
                    StockMinimo = inventario.StockMinimo
                };
                _context.Add(nuevoInventario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
            return View(inventario);
        }

        // GET: Inventarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventario = await _context.Inventarios.FindAsync(id);
            if (inventario == null)
            {
                return NotFound();
            }
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
            return View(inventario);
        }

        // POST: Inventarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ArticuloId,TallaId,StockActual,StockMinimo")] Inventario inventario)
        {
            if (id != inventario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inventario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventarioExists(inventario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArticuloId"] = new SelectList(_context.Articulos, "Id", "Nombre", inventario.ArticuloId);
            ViewData["TallaId"] = new SelectList(_context.Tallas, "Id", "Descripcion", inventario.TallaId);
            return View(inventario);
        }

        // GET: Inventarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventario = await _context.Inventarios
                .Include(i => i.Articulo)
                .Include(i => i.Talla)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inventario == null)
            {
                return NotFound();
            }

            return View(inventario);
        }

        // POST: Inventarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Este DELETE activa el trigger INSTEAD OF DELETE tr_Inventario_PreventDelete
            await _context.Database.ExecuteSqlRawAsync("DELETE FROM Inventario WHERE Id = @p0", id);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool InventarioExists(int id)
        {
            return _context.Inventarios.Any(e => e.Id == id);
        }
    }
}

MarineMexico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarineMexico</title>
    <link rel="stylesheet" href="~/MarineMexico.styles.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    
    <header>
        @* <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li> *@
        <nav id="main-nav" class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
                    SSA Marine Mexico
                </a>
                <button class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </button>
            </div>

            <div class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            Inventario
                        </a>

                        <div class="navbar-dropdown">
                            <a class="navbar-item" asp-area="" asp-controller="Inventarios" asp-action="Index">
                                Registro de inventario
                            </a>
                            <a class="navbar-item" asp-area="" asp-controller="MovimientosInventarios" asp-action="Index">
                                Movimientos
                            </a>
                            <a class="navbar-item" asp-area="" asp-controller="Articulos" asp-action="Index">
                                Artículos
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-3 p-3">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/js/all.min.js" integrity="sha512-b+nQTCdtTBIRIbraqNEwsjB6UvL3UEMkXnhzd8awtCYh0Kcsjl9uEgwVFVbhoj3uu1DO1ZMacNvLoyJJiNfcvg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>